backend:
  name: git-gateway
  branch: matsuko-ca

media_folder: static/img
public_folder: /img

collections:

  - name: "page"
    label: "Page"
    folder: src/pages
    slug: "{{slug}}"
    create: true
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "page"
      - label: "Publish Date"
        name: "date"
        widget: "date"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - label: "Link Text"
            name: "text"
            widget: "string"
          - label: "Link URL"
            name: "url"
            widget: "string"
            pattern: ['https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
', "Must be a valid URL. (e.g. https://www.google.com)"]
      - label: "Content"
        name: "content"
        widget: "list"
        types:
          - label: "Body"
            name: "Body"
            widget: "object"
            fields:
              - label: "Body"
                name: "body"
                widget: "markdown"
          - label: "Projects Listing"
            name: "ProjectsListing"
            widget: "object"
          - label: "Homepage Hero"
            name: "HomepageHero"
            widget: "object"

  - name: "project"
    label: "Project"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "project"
      - label: "Publish Date"
        name: "date"
        widget: "date"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Thumbnail"
        name: "thumbnail"
        widget: image
        allow_multiple: false
      - label: "Project Type"
        name: "projectType"
        widget: "select"
        options: ["Website", "Landing Page", "Other"]
      - label: "Technologies"
        name: "technologies"
        widget: "list"
        required: false
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - label: "Link Text"
            name: "text"
            widget: "string"
          - label: "Link URL"
            name: "url"
            widget: "string"
            pattern: ['https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
', "Must be a valid URL. (e.g. https://www.google.com)"]
      - label: "Body"
        name: "body"
        widget: "markdown"
