backend:
  name: git-gateway
  branch: matsuko-ca

media_folder: static/img
public_folder: /img

common_fields:
  title: &title
    label: Title
    name: title
    widget: string

  publishDate: &publish_date
    label: Publish Date
    name: date
    widget: date

  links: &links
    label: Links
    name: links
    widget: list
    required: false
    fields:
      - label: Link Text
        name: text
        widget: string
      - label: Link URL
        name: url
        widget: string
        pattern: ['https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
  ', Must be a valid URL. (e.g. https://www.google.com)]

  seo: &seo
    label: SEO
    name: seo
    widget: object
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text

  hero: &hero
    label: Hero
    name: hero
    widget: object
    fields:
      - label: Headline
        name: headline
        widget: string
      - label: Subheadline
        name: subheadline
        widget: string
      - label: Body
        name: body
        widget: markdown

collections:
  - name: page
    label: Page
    folder: src/pages
    slug: "{{slug}}"
    create: true
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: page
      - <<: *title
      - <<: *publish_date
      - <<: *seo
      - <<: *links
      - <<: *hero
      - label: Content
        name: content
        widget: list
        types:
          - label: Body
            name: Body
            widget: object
            fields:
              - label: Body
                name: body
                widget: markdown
          - label: Projects Listing
            name: ProjectsListing
            widget: object

  - name: project
    label: Project
    folder: src/pages/projects
    create: true
    slug: "{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: project
      - <<: *title
      - <<: *publish_date
      - <<: *seo
      - label: Thumbnail
        name: thumbnail
        widget: image
        allow_multiple: false
      - label: Project Type
        name: projectType
        widget: select
        options: [Website, Landing Page, Other]
      - label: Technologies
        name: technologies
        widget: list
        required: false
      - <<: *links
      - <<: *hero
      - label: Body
        name: body
        widget: markdown
